---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube2iam:priv
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: ["pks-privileged"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube2iam:priv
subjects:
- kind: ServiceAccount
  name: kube2iam
  namespace: kube2iam
roleRef:
  kind: ClusterRole
  name: kube2iam:priv
  apiGroup: rbac.authorization.k8s.io